// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWM81XBJn0kgNt8rCIBjO8ggwqvZe36xQ',
    appId: '1:746335666026:web:07e3c2ce4b43e074ccef13',
    messagingSenderId: '746335666026',
    projectId: 'tayotaxi-bc7b6',
    authDomain: 'tayotaxi-bc7b6.firebaseapp.com',
    storageBucket: 'tayotaxi-bc7b6.firebasestorage.app',
    measurementId: 'G-N4WYK9N8SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoA7jcNk9RovOJGjWDh9CQbh-YFNALdm8',
    appId: '1:746335666026:android:9f483690f158bd13ccef13',
    messagingSenderId: '746335666026',
    projectId: 'tayotaxi-bc7b6',
    storageBucket: 'tayotaxi-bc7b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNaIMsXC-DEui4eW3eSM9AcRFbyg_LccQ',
    appId: '1:746335666026:ios:23e8d5df6413e50dccef13',
    messagingSenderId: '746335666026',
    projectId: 'tayotaxi-bc7b6',
    storageBucket: 'tayotaxi-bc7b6.firebasestorage.app',
    iosBundleId: 'com.example.tayotaxiDriver',
  );
}
